### ISSUE TITLE
[GitHub Add-on] Disable back button after logout

### ISSUE THREAD

**Issue by aandis** [gsuitedevs/add-ons-samples#28]
Steps to reproduce 
1. Goto `Settings` -> `Disconnect Account`
1. User is taken to the auth screen but there's still a back button at the top allowing user to go back to the `Settings` screen.

**Comment by aandis** [comment]
I'm facing the same issue in an addon of my own so I'm curious how would we go about fixing this. The auth screen is built by throwing an exception -

```
    CardService.newAuthorizationException()
      .setAuthorizationUrl(githubClient().authorizationUrl())
      .setResourceDisplayName("GitHub")
      .setCustomUiCallback("handleAuthorizationRequired")
      .throwException();
```

It looks like the resulting card is pushed to the top of the stack instead of replacing the root card.

**Comment by aandis** [comment]
cc: @erickoledadevrel

**Comment by erickoledadevrel** [comment]
Which sample in this repo are you referring to?

**Comment by aandis** [comment]
Ah sorry. The [github](https://github.com/gsuitedevs/gmail-add-ons-samples/tree/master/github) sample.

**Comment by sqrrrl** [comment]
Will fix this -- right way to do this is to return a navigation that pops to the root then updates that card with the logged out state. e.g.

```
var loggedOutCard = ...; // Whatever new root state should be.
var nav = CardService.newNavigation()
  .popToRoot()
  .updateCard(loggedOutCard);
return CardService.newActionResponseBuilder()
  .setNavigation(nav)
  .setStateChanged(true)
  .build();
```
