### ISSUE TITLE
Clone which script?

### ISSUE THREAD

**Issue by ydax** [gsuitedevs/add-ons-samples#38]
Howdy. In your replication instructions, after we're told to use clasp to create the "Meeting Assistant" project, clasp will ask us which kind of project to create
`? Clone which script? 
❯ standalone 
  docs 
  sheets 
  slides 
  forms 
  webapp 
  api `

This isn't specified in the instructions, but it should be. Thanks!

**Comment by sqrrrl** [comment]
Updated the clasp commands in the readme in #40
